{% set name = "requirements-detector" %}
{% set version = "1.2.2" %}
{% set sha256 = "3642cd7a5b261d79536c36bb7ecacf2adabd902d2e0e42bfb2ba82515da10501" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/requirements_detector-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - poetry-core

  run:
    - python >=3.8
    - setuptools
    - astroid >=2.0
    - packaging >=21.3
    - semver
    - toml >=0.10.2

test:
  imports:
    - requirements_detector

about:
  home: https://github.com/landscapeio/requirements-detector
  license: MIT
  license_file: LICENSE
  summary: Python tool to find and list requirements of a Python project

extra:
  recipe-maintainers:
    - jakirkham
    - valeriupredoi
    - zklaus
