{% set name = "requirements-detector" %}
{% set version = "1.1.0" %}
{% set sha256 = "246bd23867c12061eadb346a6fe2e616f0b64e681936154a76c494a27cda3ea8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/requirements_detector-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.7,<4.0
    - pip
    - poetry-core

  run:
    - python >=3.7,<4.0
    - setuptools
    - astroid >=2.0
    - packaging >=21.3
    - toml >=0.10.2
    - poetry-semver >=0.1.0

test:
  imports:
    - requirements_detector

about:
  home: https://github.com/landscapeio/requirements-detector
  license: MIT
  license_file: LICENSE
  summary: Python tool to find and list requirements of a Python project

extra:
  recipe-maintainers:
    - jakirkham
