{% set name = "requirements-detector" %}
{% set version = "1.3.2" %}
{% set sha256 = "af5a3ea98ca703d14cf7b66751b2aeb3656d02d9e5fc1c97d7d4da02b057b601" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/requirements_detector-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core

  run:
    - python >={{ python_min }},<4
    - setuptools
    - astroid >=3.0
    - packaging >=21.3
    - semver >=3.0.0
    - toml >=0.10.2

test:
  requires:
    - python {{ python_min }}
  imports:
    - requirements_detector

about:
  home: https://github.com/landscapeio/requirements-detector
  license: MIT
  license_file: LICENSE
  summary: Python tool to find and list requirements of a Python project

extra:
  recipe-maintainers:
    - jakirkham
    - valeriupredoi
    - zklaus
