{% set name = "requirements-detector" %}
{% set version = "0.7" %}
{% set sha256 = "0d1e13e61ed243f9c3c86e6cbb19980bcb3a0e0619cde2ec1f3af70fdbee6f7b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 4
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip

  run:
    - python
    - setuptools
    - astroid >=1.4

test:
  imports:
    - requirements_detector

about:
  home: https://github.com/landscapeio/requirements-detector
  license: MIT
  license_file: LICENSE
  summary: Python tool to find and list requirements of a Python project

extra:
  recipe-maintainers:
    - jakirkham
