{% set name = "requirements-detector" %}
{% set version = "1.3.1" %}
{% set sha256 = "b89e34faf0e4d17f5736923918bd5401949cbe723294ccfefd698b3cda28e676" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/requirements_detector-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8,<4
    - pip
    - poetry-core

  run:
    - python >=3.8,<4
    - setuptools
    - astroid >=3.0
    - packaging >=21.3
    - semver >=3.0.0
    - toml >=0.10.2

test:
  imports:
    - requirements_detector

about:
  home: https://github.com/landscapeio/requirements-detector
  license: MIT
  license_file: LICENSE
  summary: Python tool to find and list requirements of a Python project

extra:
  recipe-maintainers:
    - jakirkham
    - valeriupredoi
    - zklaus
